apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: req-counter-hpa
  namespace: req-counter-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: req-counter-deployment
  minReplicas: 50
  maxReplicas: 150
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50